### PR TITLE
Depend on replacement for Node core stream (Readable)

### PR DESCRIPTION
**Pull request by Borewit**
Solves #297 by depending on [readable-stream](https://github.com/nodejs/readable-stream).

Related #296.

### CODE REVIEW

**Comment by Borewit** [comment]
@sindresorhus can you please review this?

Do you see any issues with this approach?

**Comment by sindresorhus** [comment]
I'm lukewarm on it. It does solve the issue, but it will slightly bloat Node.js installs. I guess you should add it since you promise browser support.

The reason this is happening now: https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1

**Comment by Borewit** [comment]
Thanks for review @sindresorhus. 

> I'm lukewarm on it. It does solve the issue, but it will slightly bloat Node.js installs. I guess you should add it since you promise browser support.

I see your point. This is in principle solvable by moving the browser support into a different module depending on [file-type](https://github.com/sindresorhus/file-type). That is something I proposed to you before, which you rejected in favor of having a single module. Which is a very valid argument. Yet, if you prefer to keep [file-type](https://github.com/sindresorhus/file-type) a Node.js, without any dependencies solely to make Node.js things running in the front-end I don't mind to work on this transition.

> The reason this is happening now: https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1

Great article. The way I see it, is that the browser community piggy bagged on module system from Node.js. Although the front end and server side support the same JavaScript language, their API's are fundamentally different, which even counts for things which potentially could have been the same or aligned, like streams. This makes it hard write common components which potentially could run in both domains, have to deal with these differences, and that is the reason why modules like this one, converting similar API's from one domain into the other exist.

**Comment by sindresorhus** [comment]
> This is in principle solvable by moving the browser support into a different module depending on file-type. That is something I proposed to you before, which you rejected in favor of having a single module. Which is a very valid argument. Yet, if you prefer to keep file-type a pure Node.js (no dependencies solely to make Node.js things running in the front-end) I don't mind to work on this transition.

I don't think it's worth the effort. You should merge this. It's solves the problem the best. Hopefully, Node.js will eventually support Web Streams (https://twitter.com/jasnell/status/1320796505880457216).

**Comment by Borewit** [comment]
Part of [v3.0.0](https://github.com/Borewit/readable-web-to-node-stream/releases/tag/v3.0.0)

**Pull request merged**
